on:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      JUSTIFI_API_URL: https://justifi-node-sdk.test
    strategy:
      fail-fast: true
      matrix:
        node: [21, 22, 23, 24]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
      - run: npm run lint
